name: Java CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'
        java-package: jdk+fx
    - name: print Java version
      run: java -version
    - name: Build with Maven
      run: mvn package --file src/pom.xml
